---
title: "Student Performance Predictions"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
student_por = read.csv('student+performance/student-por.csv', sep = ';',  stringsAsFactors = TRUE)
student_math = read.csv('student+performance/student-mat.csv', sep = ';', stringsAsFactors = TRUE)
all_data = rbind(student_por, student_math)
summary(all_data)
```

```{r}
head(all_data)
write.csv(all_data, 'student+performance/merged_data.csv', row.names = FALSE)
```

Covariance
```{r}
library(corrplot)
numAll = all_data[ ,sapply(all_data, is.numeric)]
corrMat = cor(numAll)
corrplot(corrMat)
```

```{r}
par(mfrow = c(2, 3))
namesInData = names(all_data)
for (i in namesInData){
  if (i != "G3") {
    boxplot(all_data$G3 ~ all_data[, i], xlab = i, ylab = "Final Grade")
  }
  
}
```
- We see that study time gives a higher final grade along with G1 and G2, which are first and second period grades for the class. We notice the the number of failures the student has had gives and impact for the final grade of there current class. 
```{r}
par(mfrow = c(2, 3))
namesInData = names(all_data)
for (i in namesInData){
  if (i != "G3") {
      plot(all_data$G3 ~ all_data[, i], xlab = i, ylab = "Final Grade")
  }
  
}
```
```{r}
set.seed(1)
n = nrow(all_data)
percentTrain = .7
trainIdx = sample(1:n, n*percentTrain)

allLinearFit = lm(G3 ~ ., all_data[trainIdx,])
testData = all_data[-trainIdx,]

summary(allLinearFit)
preds = predict(allLinearFit, testData)
sqrt(mean((testData$G3 - preds)^2))
```

```{r}

linearFit = lm(G3 ~ G1 + G2 + studytime + failures, all_data[trainIdx, ])
summary(linearFit)

preds = predict(linearFit, all_data[-trainIdx, ])
sqrt(mean((all_data[-trainIdx,]$G3 - preds)^2))
```


```{r}
nullFit = lm(G3 ~ 1, all_data[trainIdx, ])
fullFit = lm(G3 ~ ., all_data[trainIdx, ])

forward_model = step(nullFit, scope = list(lower = nullFit, upper = fullFit), direction = "forward", trace = F)
summary(forward_model)
preds = predict(forward_model, all_data[-trainIdx, ])
sqrt(mean((all_data[-trainIdx, ]$G3 - preds)^2))
```

```{r}
plot(preds, all_data[-trainIdx, ]$G3,
     xlab = "Predicted G3", ylab = "Actual G3",
     main = "Predicted vs Actual Final Grades")
abline(0, 1, col = "red")

```